package com.theouterworld.item;

import com.theouterworld.OuterWorldMod;
import com.theouterworld.block.CorrodedBlocks;
import com.theouterworld.block.ModBlocks;
import net.fabricmc.fabric.api.creativetab.v1.FabricCreativeModeTab;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;

public class ModItemGroups {
	public static final CreativeModeTab OUTER_WORLD_GROUP = Registry.register(
		BuiltInRegistries.CREATIVE_MODE_TAB,
		OuterWorldMod.id("outerworlds"),
		FabricCreativeModeTab.builder()
			.icon(() -> new ItemStack(ModBlocks.REGOLITH))
			.title(Component.translatable("itemgroup.theouterworlds"))
			.displayItems((displayContext, entries) -> {
				entries.accept(ModBlocks.RIFT);
				entries.accept(ModBlocks.RIFT_PAD);
				entries.accept(ModBlocks.BEACON_CONCENTRATOR);
				entries.accept(ModBlocks.REGOLITH);
				entries.accept(ModBlocks.SUSPICIOUS_REGOLITH);
				entries.accept(ModBlocks.OXIDIZED_BASALT);
				entries.accept(ModBlocks.OXIDIZED_BASALT_PEBBLE);
				entries.accept(ModBlocks.ANORTHOSITE);
				entries.accept(ModBlocks.ANORTHOSITE_COPPER_ORE);
				entries.accept(ModBlocks.ANORTHOSITE_GOLD_ORE);
				entries.accept(ModBlocks.ANORTHOSITE_OXIDIZED_IRON_ORE);
				entries.accept(ModBlocks.ANORTHOSITE_REDSTONE_ORE);
				entries.accept(ModBlocks.RAW_HEMATITE);
				entries.accept(ModItems.HEMATITE);
				entries.accept(ModItems.REDSTEEL_INGOT);
				entries.accept(ModItems.REDSTEEL_UPGRADE_SMITHING_TEMPLATE);
				entries.accept(ModItems.ORBIT_SMITHING_TEMPLATE);
				entries.accept(ModItems.REDSTEEL_SWORD);
				entries.accept(ModItems.REDSTEEL_SHOVEL);
				entries.accept(ModItems.REDSTEEL_PICKAXE);
				entries.accept(ModItems.REDSTEEL_AXE);
				entries.accept(ModItems.REDSTEEL_HOE);
				entries.accept(ModItems.REDSTEEL_HELMET);
				entries.accept(ModItems.REDSTEEL_CHESTPLATE);
				entries.accept(ModItems.REDSTEEL_LEGGINGS);
				entries.accept(ModItems.REDSTEEL_BOOTS);
				entries.accept(ModItems.REDSTEEL_SPEAR);
				entries.accept(ModItems.RAW_NICKEL);
				entries.accept(ModItems.NICKEL_INGOT);
				entries.accept(ModItems.NICKEL_NUGGET);
				entries.accept(ModItems.NICKEL_SWORD);
				entries.accept(ModItems.NICKEL_SHOVEL);
				entries.accept(ModItems.NICKEL_PICKAXE);
				entries.accept(ModItems.NICKEL_AXE);
				entries.accept(ModItems.NICKEL_HOE);
				entries.accept(ModItems.NICKEL_HELMET);
				entries.accept(ModItems.NICKEL_CHESTPLATE);
				entries.accept(ModItems.NICKEL_LEGGINGS);
				entries.accept(ModItems.NICKEL_BOOTS);
				entries.accept(ModItems.NICKEL_SPEAR);
				entries.accept(ModItems.OPALINE_NICKEL);
				entries.accept(ModItems.OPALINE_NICKEL_FLAIL);
				entries.accept(ModItems.OPAL_LENS);
				entries.accept(ModBlocks.NICKEL_BLOCK);
				entries.accept(ModBlocks.CUT_NICKEL);
				entries.accept(ModBlocks.CUT_NICKEL_STAIRS);
				entries.accept(ModBlocks.CUT_NICKEL_SLAB);
				entries.accept(ModBlocks.NICKEL_GRATE);
				entries.accept(ModBlocks.NICKEL_BULB);
				entries.accept(ModBlocks.NICKEL_DOOR);
				entries.accept(ModBlocks.NICKEL_TRAPDOOR);
				entries.accept(ModBlocks.NICKEL_CHAIN);
				entries.accept(ModBlocks.NICKEL_BARS);
				entries.accept(ModBlocks.PYROXENITE);
				entries.accept(ModBlocks.PYROXENITE_STAIRS);
				entries.accept(ModBlocks.PYROXENITE_SLAB);
				entries.accept(ModBlocks.PYROXENITE_WALL);
				entries.accept(ModBlocks.POLISHED_PYROXENITE);
				entries.accept(ModBlocks.POLISHED_PYROXENITE_STAIRS);
				entries.accept(ModBlocks.POLISHED_PYROXENITE_SLAB);
				entries.accept(ModBlocks.POLISHED_PYROXENITE_WALL);
				entries.accept(ModBlocks.PYROXENITE_NICKEL_ORE);
				entries.accept(ModBlocks.NORITE);
				entries.accept(ModBlocks.NORITE_STAIRS);
				entries.accept(ModBlocks.NORITE_SLAB);
				entries.accept(ModBlocks.NORITE_WALL);
				entries.accept(ModBlocks.GABBRO);
				entries.accept(ModBlocks.GABBRO_STAIRS);
				entries.accept(ModBlocks.GABBRO_SLAB);
				entries.accept(ModBlocks.GABBRO_WALL);
				entries.accept(ModBlocks.ANORTHOSITIC_REGOLITH);
				entries.accept(ModBlocks.OPAL_BLOCK);
				entries.accept(ModBlocks.RAW_OLIVINE);
				entries.accept(ModBlocks.RAW_OLIVINE_BUD);
				entries.accept(ModBlocks.OLIVINE_CRYSTAL_0);
				entries.accept(ModBlocks.OLIVINE_CRYSTAL_1);
				entries.accept(ModBlocks.OLIVINE_CRYSTAL_2);
				entries.accept(ModItems.OLIVINE_TORCH);
				entries.accept(ModBlocks.RAW_JAROSITE);
				entries.accept(ModItems.JAROSITE);
				entries.accept(ModItems.JAROSITE_ROCKET);
				entries.accept(ModBlocks.RAW_PERCHLORATE);
				entries.accept(ModItems.PERCHLORATE_CRYSTAL);
				entries.accept(ModBlocks.PERCHLORATE_CHARGE);
				entries.accept(ModBlocks.OXIDIZED_BASALT_OPAL_ORE);
				entries.accept(ModBlocks.ANORTHOSITE_OPAL_ORE);
				entries.accept(ModItems.OPAL);
				entries.accept(ModItems.ROVER_POTTERY_SHERD);
				entries.accept(ModItems.RAW_OXIDIZED_IRON);
				entries.accept(ModItems.OXIDIZED_BASALT_ROCK);
				entries.accept(ModItems.OXIDIZED_BASALT_PICK);
				entries.accept(ModItems.OXIDIZED_BASALT_SWORD);
				entries.accept(ModItems.OXIDIZED_BASALT_AXE);
				entries.accept(ModItems.OXIDIZED_BASALT_PICKAXE);
				entries.accept(ModItems.OXIDIZED_BASALT_SHOVEL);
				entries.accept(ModItems.OXIDIZED_BASALT_HOE);
				entries.accept(ModItems.RUST_SPLINT);
				entries.accept(ModBlocks.KNAPPING_TABLE);
				entries.accept(ModBlocks.PROCESSOR);
				entries.accept(ModBlocks.DRY_ICE);
				entries.accept(ModBlocks.CARBONIC_ICE);
				entries.accept(ModBlocks.ICE);
				entries.accept(ModBlocks.PACKED_ICE);
				entries.accept(ModBlocks.BLUE_ICE);
				entries.accept(ModBlocks.GYPSUM_BLOCK);
				entries.accept(ModBlocks.GYPSUM_SPIKE);
				entries.accept(ModBlocks.KHARAX_SHED);
				entries.accept(ModBlocks.KHARAX_SPORE);
				entries.accept(ModBlocks.MERCURY_BLOCK);
				entries.accept(ModItems.MERCURY_BUCKET);
				entries.accept(ModItems.KHARAX_CHITIN);
				entries.accept(ModItems.KHARAX_BELT);
				entries.accept(ModItems.KHARAX_SPAWN_EGG);
				entries.accept(ModBlocks.FROZEN_NETHER_PORTAL);

				entries.accept(ModBlocks.EXPOSED_IRON);
				entries.accept(ModBlocks.WEATHERED_IRON);
				entries.accept(ModBlocks.OXIDIZED_IRON);
				entries.accept(ModBlocks.WAXED_IRON);
				entries.accept(ModBlocks.WAXED_EXPOSED_IRON);
				entries.accept(ModBlocks.WAXED_WEATHERED_IRON);
				entries.accept(ModBlocks.WAXED_OXIDIZED_IRON);

				entries.accept(ModBlocks.CUT_IRON);
				entries.accept(ModBlocks.EXPOSED_CUT_IRON);
				entries.accept(ModBlocks.WEATHERED_CUT_IRON);
				entries.accept(ModBlocks.OXIDIZED_CUT_IRON);
				entries.accept(ModBlocks.WAXED_CUT_IRON);
				entries.accept(ModBlocks.WAXED_EXPOSED_CUT_IRON);
				entries.accept(ModBlocks.WAXED_WEATHERED_CUT_IRON);
				entries.accept(ModBlocks.WAXED_OXIDIZED_CUT_IRON);
				entries.accept(ModBlocks.CUT_IRON_SLAB);
				entries.accept(ModBlocks.EXPOSED_CUT_IRON_SLAB);
				entries.accept(ModBlocks.WEATHERED_CUT_IRON_SLAB);
				entries.accept(ModBlocks.OXIDIZED_CUT_IRON_SLAB);
				entries.accept(ModBlocks.WAXED_CUT_IRON_SLAB);
				entries.accept(ModBlocks.WAXED_EXPOSED_CUT_IRON_SLAB);
				entries.accept(ModBlocks.WAXED_WEATHERED_CUT_IRON_SLAB);
				entries.accept(ModBlocks.WAXED_OXIDIZED_CUT_IRON_SLAB);
				entries.accept(ModBlocks.CUT_IRON_STAIRS);
				entries.accept(ModBlocks.EXPOSED_CUT_IRON_STAIRS);
				entries.accept(ModBlocks.WEATHERED_CUT_IRON_STAIRS);
				entries.accept(ModBlocks.OXIDIZED_CUT_IRON_STAIRS);
				entries.accept(ModBlocks.WAXED_CUT_IRON_STAIRS);
				entries.accept(ModBlocks.WAXED_EXPOSED_CUT_IRON_STAIRS);
				entries.accept(ModBlocks.WAXED_WEATHERED_CUT_IRON_STAIRS);
				entries.accept(ModBlocks.WAXED_OXIDIZED_CUT_IRON_STAIRS);

				entries.accept(ModBlocks.IRON_BULB);
				entries.accept(ModBlocks.EXPOSED_IRON_BULB);
				entries.accept(ModBlocks.WEATHERED_IRON_BULB);
				entries.accept(ModBlocks.OXIDIZED_IRON_BULB);
				entries.accept(ModBlocks.WAXED_IRON_BULB);
				entries.accept(ModBlocks.WAXED_EXPOSED_IRON_BULB);
				entries.accept(ModBlocks.WAXED_WEATHERED_IRON_BULB);
				entries.accept(ModBlocks.WAXED_OXIDIZED_IRON_BULB);

				entries.accept(ModBlocks.EXPOSED_IRON_CHAIN);
				entries.accept(ModBlocks.WEATHERED_IRON_CHAIN);
				entries.accept(ModBlocks.OXIDIZED_IRON_CHAIN);
				entries.accept(ModBlocks.WAXED_IRON_CHAIN);
				entries.accept(ModBlocks.WAXED_EXPOSED_IRON_CHAIN);
				entries.accept(ModBlocks.WAXED_WEATHERED_IRON_CHAIN);
				entries.accept(ModBlocks.WAXED_OXIDIZED_IRON_CHAIN);

				entries.accept(ModBlocks.EXPOSED_IRON_DOOR);
				entries.accept(ModBlocks.WEATHERED_IRON_DOOR);
				entries.accept(ModBlocks.OXIDIZED_IRON_DOOR);
				entries.accept(ModBlocks.WAXED_IRON_DOOR);
				entries.accept(ModBlocks.WAXED_EXPOSED_IRON_DOOR);
				entries.accept(ModBlocks.WAXED_WEATHERED_IRON_DOOR);
				entries.accept(ModBlocks.WAXED_OXIDIZED_IRON_DOOR);

				entries.accept(ModBlocks.EXPOSED_IRON_TRAPDOOR);
				entries.accept(ModBlocks.WEATHERED_IRON_TRAPDOOR);
				entries.accept(ModBlocks.OXIDIZED_IRON_TRAPDOOR);
				entries.accept(ModBlocks.WAXED_IRON_TRAPDOOR);
				entries.accept(ModBlocks.WAXED_EXPOSED_IRON_TRAPDOOR);
				entries.accept(ModBlocks.WAXED_WEATHERED_IRON_TRAPDOOR);
				entries.accept(ModBlocks.WAXED_OXIDIZED_IRON_TRAPDOOR);

				entries.accept(ModBlocks.IRON_GRATE);
				entries.accept(ModBlocks.EXPOSED_IRON_GRATE);
				entries.accept(ModBlocks.WEATHERED_IRON_GRATE);
				entries.accept(ModBlocks.OXIDIZED_IRON_GRATE);
				entries.accept(ModBlocks.WAXED_IRON_GRATE);
				entries.accept(ModBlocks.WAXED_EXPOSED_IRON_GRATE);
				entries.accept(ModBlocks.WAXED_WEATHERED_IRON_GRATE);
				entries.accept(ModBlocks.WAXED_OXIDIZED_IRON_GRATE);

				entries.accept(ModBlocks.EXPOSED_IRON_BARS);
				entries.accept(ModBlocks.WEATHERED_IRON_BARS);
				entries.accept(ModBlocks.OXIDIZED_IRON_BARS);
				entries.accept(ModBlocks.WAXED_IRON_BARS);
				entries.accept(ModBlocks.WAXED_EXPOSED_IRON_BARS);
				entries.accept(ModBlocks.WAXED_WEATHERED_IRON_BARS);
				entries.accept(ModBlocks.WAXED_OXIDIZED_IRON_BARS);

				entries.accept(ModBlocks.IRON_GOLEM_STATUE);
				entries.accept(ModBlocks.EXPOSED_IRON_GOLEM_STATUE);
				entries.accept(ModBlocks.WEATHERED_IRON_GOLEM_STATUE);
				entries.accept(ModBlocks.OXIDIZED_IRON_GOLEM_STATUE);
				entries.accept(ModBlocks.WAXED_IRON_GOLEM_STATUE);
				entries.accept(ModBlocks.WAXED_EXPOSED_IRON_GOLEM_STATUE);
				entries.accept(ModBlocks.WAXED_WEATHERED_IRON_GOLEM_STATUE);
				entries.accept(ModBlocks.WAXED_OXIDIZED_IRON_GOLEM_STATUE);

				entries.accept(CorrodedBlocks.CORRODED_COPPER);
				entries.accept(CorrodedBlocks.CORRODED_EXPOSED_COPPER);
				entries.accept(CorrodedBlocks.CORRODED_WEATHERED_COPPER);
				entries.accept(CorrodedBlocks.CORRODED_OXIDIZED_COPPER);
				entries.accept(CorrodedBlocks.CORRODED_CUT_COPPER);
				entries.accept(CorrodedBlocks.CORRODED_EXPOSED_CUT_COPPER);
				entries.accept(CorrodedBlocks.CORRODED_WEATHERED_CUT_COPPER);
				entries.accept(CorrodedBlocks.CORRODED_OXIDIZED_CUT_COPPER);
				entries.accept(CorrodedBlocks.CORRODED_CUT_COPPER_STAIRS);
				entries.accept(CorrodedBlocks.CORRODED_EXPOSED_CUT_COPPER_STAIRS);
				entries.accept(CorrodedBlocks.CORRODED_WEATHERED_CUT_COPPER_STAIRS);
				entries.accept(CorrodedBlocks.CORRODED_OXIDIZED_CUT_COPPER_STAIRS);
				entries.accept(CorrodedBlocks.CORRODED_CUT_COPPER_SLAB);
				entries.accept(CorrodedBlocks.CORRODED_EXPOSED_CUT_COPPER_SLAB);
				entries.accept(CorrodedBlocks.CORRODED_WEATHERED_CUT_COPPER_SLAB);
				entries.accept(CorrodedBlocks.CORRODED_OXIDIZED_CUT_COPPER_SLAB);
				entries.accept(CorrodedBlocks.CORRODED_IRON);
				entries.accept(CorrodedBlocks.CORRODED_EXPOSED_IRON);
				entries.accept(CorrodedBlocks.CORRODED_WEATHERED_IRON);
				entries.accept(CorrodedBlocks.CORRODED_OXIDIZED_IRON);
				entries.accept(CorrodedBlocks.CORRODED_CUT_IRON);
				entries.accept(CorrodedBlocks.CORRODED_EXPOSED_CUT_IRON);
				entries.accept(CorrodedBlocks.CORRODED_WEATHERED_CUT_IRON);
				entries.accept(CorrodedBlocks.CORRODED_OXIDIZED_CUT_IRON);
				entries.accept(CorrodedBlocks.CORRODED_CUT_IRON_SLAB);
				entries.accept(CorrodedBlocks.CORRODED_EXPOSED_CUT_IRON_SLAB);
				entries.accept(CorrodedBlocks.CORRODED_WEATHERED_CUT_IRON_SLAB);
				entries.accept(CorrodedBlocks.CORRODED_OXIDIZED_CUT_IRON_SLAB);
				entries.accept(CorrodedBlocks.CORRODED_CUT_IRON_STAIRS);
				entries.accept(CorrodedBlocks.CORRODED_EXPOSED_CUT_IRON_STAIRS);
				entries.accept(CorrodedBlocks.CORRODED_WEATHERED_CUT_IRON_STAIRS);
				entries.accept(CorrodedBlocks.CORRODED_OXIDIZED_CUT_IRON_STAIRS);
				entries.accept(CorrodedBlocks.CORRODED_IRON_GRATE);
				entries.accept(CorrodedBlocks.CORRODED_EXPOSED_IRON_GRATE);
				entries.accept(CorrodedBlocks.CORRODED_WEATHERED_IRON_GRATE);
				entries.accept(CorrodedBlocks.CORRODED_OXIDIZED_IRON_GRATE);
				entries.accept(CorrodedBlocks.CORRODED_IRON_BULB);
				entries.accept(CorrodedBlocks.CORRODED_EXPOSED_IRON_BULB);
				entries.accept(CorrodedBlocks.CORRODED_WEATHERED_IRON_BULB);
				entries.accept(CorrodedBlocks.CORRODED_OXIDIZED_IRON_BULB);
				entries.accept(CorrodedBlocks.CORRODED_IRON_DOOR);
				entries.accept(CorrodedBlocks.CORRODED_EXPOSED_IRON_DOOR);
				entries.accept(CorrodedBlocks.CORRODED_WEATHERED_IRON_DOOR);
				entries.accept(CorrodedBlocks.CORRODED_OXIDIZED_IRON_DOOR);
				entries.accept(CorrodedBlocks.CORRODED_IRON_TRAPDOOR);
				entries.accept(CorrodedBlocks.CORRODED_EXPOSED_IRON_TRAPDOOR);
				entries.accept(CorrodedBlocks.CORRODED_WEATHERED_IRON_TRAPDOOR);
				entries.accept(CorrodedBlocks.CORRODED_OXIDIZED_IRON_TRAPDOOR);
				entries.accept(CorrodedBlocks.CORRODED_IRON_CHAIN);
				entries.accept(CorrodedBlocks.CORRODED_EXPOSED_IRON_CHAIN);
				entries.accept(CorrodedBlocks.CORRODED_WEATHERED_IRON_CHAIN);
				entries.accept(CorrodedBlocks.CORRODED_OXIDIZED_IRON_CHAIN);
				entries.accept(CorrodedBlocks.CORRODED_IRON_BARS);
				entries.accept(CorrodedBlocks.CORRODED_EXPOSED_IRON_BARS);
				entries.accept(CorrodedBlocks.CORRODED_WEATHERED_IRON_BARS);
				entries.accept(CorrodedBlocks.CORRODED_OXIDIZED_IRON_BARS);
			})
			.build()
	);

	public static void registerItemGroups() {
		OuterWorldMod.LOGGER.info("Registering item groups for {}", OuterWorldMod.MOD_ID);
	}
}
